# fly.toml app configuration file generated for clayvoices-spring-frog-8948 on 2024-11-09T13:55:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "clayvoices-spring-frog-8948"
primary_region = "lhr"

[build]

[[services]]
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Health Checks
  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

  # Concurrency Limits
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1